### ISSUE TITLE
OnTAD error

### ISSUE THREAD

**Issue by BenxiaHu** [anlin00007/OnTAD#3]
When I ran OnTAD, I got two files, one is the  .tad file.
head XX.chr3_onTAD.tad 
![image](https://user-images.githubusercontent.com/12387462/71523519-6ea98e80-2897-11ea-9e17-69f3422a5e7c.png)
 
But the coordinates between tad and bed files are totally different.
I want to plot the TAD with pyGenomeTracks. which file do I should use?
best,

**Comment by anlin00007** [comment]
The coordinates in *.tad file show the position of each TAD in the input matrix, while the *.bed file shows the genomic coordinates (min(matrix position * resolution, chrlength)). I am not very familar with pyGenomeTracks but it seems favor the *.bed file as it is designed as a track.

**Comment by BenxiaHu** [comment]
thanks for your reply. 
the TAD position should be 0, 40, 80kb or..  40xn kb on the basis of your explanation.  please take a a look at the screenshot I uploaded.

**Comment by anlin00007** [comment]
The screenshot is for *.tad file. As I explained, it shows the position of each TAD in the input matrix. For example, The second row (2, 12) suggests there is a TAD which has left boundary starts at 2nd bin and right boundary ends at 12th bin. Those are the coordinates in the matrix.
If you multiply the coordinates in the matrix with the resolution you use (e.g. 10kb), you can get the genomic coordinates, which are used in the *.bed file.

**Comment by BenxiaHu** [comment]
Thanks. I got it.
I still have another question:
when I plot the TADs with normalized matrix and TAD corrdinates(bed file), it seems that the TADs called by OnTAD are not consistent with the normalized matrix generated by hicexplorer. Do you have any good idead to improve this problem?

![image](https://user-images.githubusercontent.com/12387462/71560533-f975bf00-2a38-11ea-89ed-df6e21885b9c.png)
