### ISSUE TITLE
heatmap for TADs

### ISSUE THREAD

**Issue by BenxiaHu** [anlin00007/OnTAD#4]
when I plot the TADs with normalized matrix and TAD corrdinates(bed file), it seems that the TADs called by OnTAD are not consistent with the normalized matrix generated by hicexplorer. Do you have any good idead to improve this problem?

![image](https://user-images.githubusercontent.com/12387462/71560533-f975bf00-2a38-11ea-89ed-df6e21885b9c.png)

_Originally posted by @benxiahu in https://github.com/anlin00007/OnTAD/issues/3#issuecomment-569526967_

**Comment by anlin00007** [comment]
If you are referring 'not consistent' as different from eyeballing judgement, I wouldn't consider it as a problem as the result seems encouraging. Most of the small TADs are captured by OnTAD. The bigger ones seems not that convincing but you can certainly remove those by changing the  'maxsz' parameter. If you want to have more stringent TADs, you can also increase the 'penalty' score.

**Comment by BenxiaHu** [comment]
okay.  I will try it.  thanks
does the parameter mass refer to as the size of window(bin) or the physical distance?

**Comment by anlin00007** [comment]
the parameter 'maxsz' refers to the maximum number of bins that can be included in a TAD.
