### ISSUE TITLE
OnTAD crashes on certain chromosomes for VC and SCALE, not NONE and VC_SQRT

### ISSUE THREAD

**Issue by tolender** [anlin00007/OnTAD#9]
I am finding that when I run OnTAD for each chromosome using .hic files that only when I use NONE or VC_SQRT, I am able to call TADs for all chromosomes. There are mappability artefacts that miss-call some TADs/subTADs when using NONE or VC_SQRT, so I want to use KR. However, when I use VC or KR normalization, all .hic files I try will call TADs for some chromosomes and not for others. 

For the chromosomes that do not finish:
1) Cumsum data: reaches 100%
2) Calculate score: reaches 100%  
3) Find local min: reaches 100%
4) Normalize data: reaches 100%
5) Call TADs: reaches about 10-30%, skips to 100%, then says:
"100% [.........................] Done 7.579sec (29.318sec) | score=0.000, tadn=0
Completed!"

This is also random because each file has different chromosomes that fail...... 
Is there a problem with the data that causes it to crash? What is the problem here and why is it only for KR/VC normalization?

**Comment by anlin00007** [comment]
Hello,

It might be related with memory usage. VC and KR normalized files contains decimals and are larger than the count matrix. Some long chromosomes like Chr 1 & 2 will consume high amount of memory. You may consider increase the memory on your computing machine/cloud, or chunk the large chromosomes into small pieces.

**Comment by tolender** [comment]
Hi,
Thank you for the quick response. 
I verified for chromosomes that crashed using KR that they do not exceed the memory usage. I've tried as high as 1000G RAM but the usage for chr1 for example didn't exceed 16GB. Also it does not appear to be dependent on chromatin size as some samples will call chr1 and chr2 but crash on smaller chromosomes.
